// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1ZfTtC6hFBsuZaxNjGfiNE3yqDZxV_z0',
    appId: '1:73858106642:web:95b25c716219829fe45fcb',
    messagingSenderId: '73858106642',
    projectId: 'peliculas-f54d2',
    authDomain: 'peliculas-f54d2.firebaseapp.com',
    storageBucket: 'peliculas-f54d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDkpZ5fDZKae0QANiQ_Cmeep0tLVS1qSU',
    appId: '1:73858106642:android:eee2a31c269c6932e45fcb',
    messagingSenderId: '73858106642',
    projectId: 'peliculas-f54d2',
    storageBucket: 'peliculas-f54d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-JV_VWi7inzFReMUkfUzT7GNppjY2SfE',
    appId: '1:73858106642:ios:6efad741ba65f482e45fcb',
    messagingSenderId: '73858106642',
    projectId: 'peliculas-f54d2',
    storageBucket: 'peliculas-f54d2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-JV_VWi7inzFReMUkfUzT7GNppjY2SfE',
    appId: '1:73858106642:ios:6efad741ba65f482e45fcb',
    messagingSenderId: '73858106642',
    projectId: 'peliculas-f54d2',
    storageBucket: 'peliculas-f54d2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1ZfTtC6hFBsuZaxNjGfiNE3yqDZxV_z0',
    appId: '1:73858106642:web:53a3f83328151f24e45fcb',
    messagingSenderId: '73858106642',
    projectId: 'peliculas-f54d2',
    authDomain: 'peliculas-f54d2.firebaseapp.com',
    storageBucket: 'peliculas-f54d2.firebasestorage.app',
  );
}
